### ISSUE TITLE
shareReplay needs more explanation

### ISSUE THREAD

**Issue by SebastianStehle** [btroncone/learn-rxjs#194]
Hi,

I just stumbled over the following behavior:

https://github.com/ReactiveX/rxjs/issues/4530

I think the operator needs more explanation, have not found any official docs for this yet.

**Comment by btroncone** [comment]
Thanks, will look into this! 👍

**Comment by rozpuszczalny** [comment]
Hi, thanks for awesome site!
I think that having `shareReplay({refCount: true})` described will be very beneficial, since this feature is very powerful in terms of creating for example API calls every interval only if subscribers are present (`interval` source + `switchMap` with API call + `shareReplay({refCount: true})`)

**Comment by btroncone** [comment]
Closing - cleaning up old issues.
